apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

components:
  - github.com/ocm-sop/apps-domain-tls-cert?ref=main

resources: 
  - namespace.yaml
  - public-vault-tls-cert.yaml
  - private-vault-tls-cert.yaml