apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

resources: 
  - public-vault-tls.yaml
  - public-vault-tls-cert.yaml
  - private-vault-tls.yaml
  - private-vault-tls-cert.yaml